import { useLocation, Link } from 'react-router-dom'
import { useState } from 'react'
import { AlertTriangle, CheckCircle, Phone, FileText, ArrowRight, Shield, BookOpen, Calculator, Loader2 } from 'lucide-react'
import { apiFetch } from '../utils/api'

export default function ResultsPage() {
  const location = useLocation()
  const data = location.state
  const [confirmedActions, setConfirmedActions] = useState<Set<number>>(new Set())
  const [sbar, setSbar] = useState<any>(null)
  const [referral, setReferral] = useState<any>(null)
  const [loading, setLoading] = useState(false)

  if (!data) return <div className="text-center py-12"><p className="text-gray-500">No assessment data. <Link to="/assess" className="text-rose-700 underline">Run an assessment</Link></p></div>

  const riskConfig: Record<string, { bg: string; border: string; text: string }> = {
    critical: { bg: 'bg-red-100', border: 'border-red-500', text: 'text-red-800' },
    high: { bg: 'bg-orange-100', border: 'border-orange-500', text: 'text-orange-800' },
    moderate: { bg: 'bg-yellow-100', border: 'border-yellow-500', text: 'text-yellow-800' },
    low: { bg: 'bg-green-100', border: 'border-green-500', text: 'text-green-800' },
  }
  const rc = riskConfig[data.risk_level] || riskConfig.low

  const handleConfirm = async (idx: number) => {
    setConfirmedActions(prev => new Set(prev).add(idx))
    await apiFetch(`/api/v1/assess/${data.assessment_id}/confirm-action?action_index=${idx}&confirmed_by=demo-clinician`, { method: 'POST' })
  }

  const generateSBAR = async () => {
    setLoading(true)
    const res = await apiFetch(`/api/v1/assess/${data.assessment_id}/sbar`, { method: 'POST' })
    setSbar(await res.json())
    setLoading(false)
  }

  const generateReferral = async () => {
    setLoading(true)
    const res = await apiFetch(`/api/v1/assess/${data.assessment_id}/referral`, { method: 'POST' })
    setReferral(await res.json())
    setLoading(false)
  }

  return (
    <div className="space-y-4">
      <div className={`rounded-xl border-l-4 p-5 ${rc.bg} ${rc.border}`}>
        <div className="flex items-center gap-3">
          <AlertTriangle className={`w-8 h-8 ${rc.text}`} />
          <div>
            <h2 className={`text-2xl font-black uppercase ${rc.text}`}>{data.risk_level} RISK</h2>
            <p className="text-sm opacity-80">Source: {data.guideline_source}</p>
          </div>
        </div>
      </div>

      <div className="bg-emerald-50 border border-emerald-200 rounded-lg p-3 flex items-start gap-2">
        <Shield className="w-5 h-5 text-emerald-600 shrink-0 mt-0.5" />
        <div>
          <p className="text-xs font-semibold text-emerald-800">DETERMINISTIC RULE ENGINE OUTPUT</p>
          <p className="text-xs text-emerald-700">Risk level, red flags, and actions generated by validated clinical rules — not an LLM.</p>
        </div>
      </div>

      {data.red_flags?.length > 0 && (
        <div className="bg-white rounded-lg shadow p-4">
          <h3 className="font-bold text-red-700 mb-2 flex items-center gap-2"><AlertTriangle className="w-5 h-5" /> Red Flags Detected</h3>
          <ul className="space-y-2">
            {data.red_flags.map((f: string, i: number) => (
              <li key={i} className="flex items-start gap-2 text-sm bg-red-50 p-2 rounded"><span className="text-red-500 font-bold">!</span><span className="text-red-900 font-medium">{f}</span></li>
            ))}
          </ul>
        </div>
      )}

      {data.missing_critical_info?.length > 0 && (
        <div className="bg-amber-50 rounded-lg border border-amber-200 p-4">
          <h3 className="font-semibold text-amber-800 mb-2">Missing Critical Information</h3>
          <ul className="list-disc list-inside text-sm text-amber-900 space-y-0.5">
            {data.missing_critical_info.map((m: string, i: number) => <li key={i}>{m}</li>)}
          </ul>
        </div>
      )}

      <div className="bg-white rounded-lg shadow">
        <div className="p-4 border-b">
          <h3 className="font-bold text-gray-800 flex items-center gap-2"><CheckCircle className="w-5 h-5" /> Prioritized Action Checklist</h3>
          <p className="text-xs text-gray-500 mt-1">Confirm each action after completion. All require human verification.</p>
        </div>
        <div className="divide-y">
          {data.actions?.map((action: any, idx: number) => {
            const isConfirmed = confirmedActions.has(idx)
            const catColors: Record<string, string> = {
              immediate: 'bg-red-100 text-red-700 border-red-200', urgent: 'bg-orange-100 text-orange-700 border-orange-200',
              escalation: 'bg-purple-100 text-purple-700 border-purple-200', calculation: 'bg-blue-100 text-blue-700 border-blue-200',
              documentation: 'bg-gray-100 text-gray-700 border-gray-200',
            }
            return (
              <div key={idx} className={`p-4 ${isConfirmed ? 'bg-green-50' : ''}`}>
                <div className="flex items-start gap-3">
                  <div className="shrink-0">
                    <span className={`inline-block w-8 h-8 rounded-full flex items-center justify-center text-sm font-bold ${isConfirmed ? 'bg-green-500 text-white' : 'bg-gray-200 text-gray-600'}`}>{isConfirmed ? '✓' : action.priority}</span>
                  </div>
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 flex-wrap">
                      <span className={`text-[10px] font-bold px-2 py-0.5 rounded border ${catColors[action.category] || 'bg-gray-100'}`}>{action.category.toUpperCase()}</span>
                      {action.source_guideline && <span className="text-[10px] text-gray-400 flex items-center gap-0.5"><BookOpen className="w-3 h-3" /> {action.source_guideline}</span>}
                    </div>
                    <p className={`font-medium mt-1 ${isConfirmed ? 'line-through text-gray-400' : 'text-gray-900'}`}>{action.description}</p>
                    {action.rationale && <p className="text-xs text-gray-500 mt-1 italic">{action.rationale}</p>}
                    {action.detailed_steps && (
                      <ol className="mt-2 space-y-1">
                        {action.detailed_steps.map((step: string, si: number) => (
                          <li key={si} className="text-xs text-gray-600 flex items-start gap-1.5"><ArrowRight className="w-3 h-3 text-gray-400 mt-0.5 shrink-0" />{step}</li>
                        ))}
                      </ol>
                    )}
                    {action.medication_calculation && (
                      <div className="mt-2 bg-blue-50 border border-blue-100 rounded p-2">
                        <div className="flex items-center gap-1 text-blue-800 text-xs font-semibold mb-1"><Calculator className="w-3 h-3" /> Deterministic Calculation</div>
                        <pre className="text-[11px] text-blue-900 overflow-x-auto">{JSON.stringify(action.medication_calculation, null, 2)}</pre>
                      </div>
                    )}
                    {action.contraindications?.length > 0 && (
                      <div className="mt-2 bg-red-50 border border-red-100 rounded p-2">
                        <p className="text-xs text-red-700 font-semibold">⚠️ Safety Checks:</p>
                        {action.contraindications.map((c: string, ci: number) => <p key={ci} className="text-xs text-red-600">{c}</p>)}
                      </div>
                    )}
                    {action.requires_confirmation && !isConfirmed && (
                      <button onClick={() => handleConfirm(idx)} className="mt-3 w-full py-2 bg-rose-700 text-white text-sm font-semibold rounded-lg hover:bg-rose-800">Confirm Action Completed</button>
                    )}
                    {isConfirmed && <p className="mt-2 text-xs text-green-700 font-medium flex items-center gap-1"><CheckCircle className="w-3 h-3" /> Confirmed by clinician</p>}
                  </div>
                </div>
              </div>
            )
          })}
        </div>
      </div>

      <div className="bg-white rounded-lg shadow p-4">
        <h3 className="font-semibold text-gray-800 mb-2">Monitoring Recommendations</h3>
        <ul className="space-y-1.5">
          {data.monitoring_recommendations?.map((m: string, i: number) => (
            <li key={i} className="text-sm text-gray-700 flex items-start gap-2"><span className="w-1.5 h-1.5 bg-gray-400 rounded-full mt-1.5 shrink-0" />{m}</li>
          ))}
        </ul>
      </div>

      {data.escalation_threshold && (
        <div className="bg-purple-50 border-2 border-purple-300 rounded-lg p-4">
          <h3 className="font-bold text-purple-900 flex items-center gap-2"><Phone className="w-5 h-5" /> Escalation Required</h3>
          <p className="text-sm text-purple-900 mt-2 font-medium">{data.escalation_threshold}</p>
        </div>
      )}

      <div className="grid grid-cols-2 gap-3">
        <button onClick={generateSBAR} disabled={loading} className="bg-white border-2 border-gray-300 text-gray-700 py-3 rounded-lg font-medium hover:border-rose-500 hover:text-rose-700 flex items-center justify-center gap-2"><FileText className="w-4 h-4" /> Generate SBAR</button>
        <button onClick={generateReferral} disabled={loading} className="bg-white border-2 border-gray-300 text-gray-700 py-3 rounded-lg font-medium hover:border-rose-500 hover:text-rose-700 flex items-center justify-center gap-2"><Phone className="w-4 h-4" /> Generate Referral</button>
      </div>

      {loading && <div className="text-center py-4"><Loader2 className="w-6 h-6 animate-spin mx-auto text-rose-600" /></div>}

      {sbar && (
        <div className="bg-white rounded-lg shadow p-4 border-l-4 border-blue-500">
          <h3 className="font-bold text-blue-900 mb-2 flex items-center gap-2"><FileText className="w-4 h-4" /> SBAR Handoff <span className="text-[10px] font-normal text-gray-400">(AI-generated from verified data)</span></h3>
          <div className="space-y-2 text-sm">
            <p><strong className="text-blue-800">S:</strong> {sbar.situation}</p>
            <p><strong className="text-blue-800">B:</strong> {sbar.background}</p>
            <p><strong className="text-blue-800">A:</strong> {sbar.assessment}</p>
            <p><strong className="text-blue-800">R:</strong> {sbar.recommendation}</p>
          </div>
        </div>
      )}

      {referral && (
        <div className="bg-white rounded-lg shadow p-4 border-l-4 border-purple-500">
          <h3 className="font-bold text-purple-900 mb-2 flex items-center gap-2"><Phone className="w-4 h-4" /> Referral Note <span className="text-[10px] font-normal text-gray-400">(AI-generated from verified data)</span></h3>
          <div className="space-y-2 text-sm">
            <p><strong>Patient:</strong> {referral.patient_summary}</p>
            <p><strong>Findings:</strong> {referral.clinical_findings}</p>
            <p><strong>Reason:</strong> {referral.reason_for_referral}</p>
            <p><strong>Urgency:</strong> <span className="font-bold text-red-600 uppercase">{referral.urgency}</span></p>
            <p><strong>Transport:</strong> {referral.transport_recommendation}</p>
          </div>
        </div>
      )}

      <div className="text-center pb-6"><Link to="/assess" className="text-rose-700 underline text-sm">Start New Assessment</Link></div>
    </div>
  )
}
